version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  streamlit:
    build: .  # path to your Streamlit Dockerfile
    ports:
      - "8555:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  api_gateway:
    build: ./api
    restart: unless-stopped
    ports:
      - "8556:8000" # Expose the gateway port
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  # frontend:
  #   build: ./options-ui
  #   restart: unless-stopped
  #   ports:
  #     - "3560:3000" # Expose the React app port
  #   depends_on:
  #     - api_gateway
  #   # Updated Frontend Service for SvelteKit
  svelte-frontend:
    build:
      context: ./options-svelte  # Assumed path to your SvelteKit app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3550:3000" # Expose the SvelteKit app port
    depends_on:
      - api_gateway